ARG NODE_BASE=node:24-alpine3.20
FROM ${NODE_BASE} AS builder
LABEL authors="Roy Francis"
LABEL desc="Encrypts static HTML files and adds a password login"
LABEL org.opencontainers.image.source="https://github.com/royfrancis/staticrypt"
RUN apk add --no-cache bash && apk upgrade --no-cache
WORKDIR /home/staticrypt

COPY package*.json ./
RUN npm ci --omit=dev

COPY cli/ cli/
COPY lib/ lib/
COPY scripts/ scripts/

FROM ${NODE_BASE}
RUN apk add --no-cache bash && apk upgrade --no-cache
WORKDIR /opt/staticrypt
COPY --from=builder /home/staticrypt .
RUN chmod +x cli/index.js && ln -s /opt/staticrypt/cli/index.js /usr/local/bin/staticrypt

WORKDIR /home/work
ENTRYPOINT ["staticrypt"]
CMD ["--version"]
